# =============================================================================
# Terraform Variables — TEST-3SG Day-0 Deployment
# Generated by Netris Fabric Terraform Builder
# =============================================================================

# Controller connection
controller_address  = "https://adam-ctl.netris.io"
controller_login    = "netris"
controller_password = "913QGAi6oQTSGgZm20eU"

# Site parameters
site_name                  = "TEST-3SG"
public_asn                 = 65500
nos                        = "cumulus_nvue"
softgate_flavor            = "sg-pro"
tenant_name                = "Admin"
inventory_profile_timezone = "Etc/GMT"
ntp_servers                = ["1.pool.ntp.org", "2.pool.ntp.org"]
dns_servers                = ["1.1.1.1", "8.8.8.8"]
acl_default_policy         = "permit"
vlan_range                 = "2-4094"
vlan_range_auto_assign     = "2-3999"
