from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any, Dict, Optional

from app.models import GlobalConfig

logger = logging.getLogger("config_sync")

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = Path(__file__).resolve().parent.parent / "data"
CONFIG_FILE = DATA_DIR / "global_config.json"


def load_global_config() -> GlobalConfig:
    """Load global config from data/global_config.json or infer from existing tool env files."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
                return GlobalConfig(**data)
        except Exception as e:
            logger.warning("Failed to load %s, falling back to defaults: %s", CONFIG_FILE, e)

    # Fallback: check netbox-netris/.env or netris-prometheus-exporter/netris.var
    cfg = GlobalConfig()
    netbox_env = REPO_ROOT / "netbox-netris" / ".env"
    if netbox_env.exists():
        try:
            with open(netbox_env, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line.startswith("NETRIS_URL="):
                        cfg.netris_url = line.split("=", 1)[1].strip()
                    elif line.startswith("NETRIS_USER="):
                        cfg.netris_username = line.split("=", 1)[1].strip()
                    elif line.startswith("NETRIS_PASSWORD="):
                        cfg.netris_password = line.split("=", 1)[1].strip()
        except Exception:
            pass

    return cfg


def save_global_config(cfg: GlobalConfig) -> None:
    """Save global config to data/global_config.json."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        json.dump(cfg.model_dump(), f, indent=2)


def sync_global_to_all_tools(cfg: GlobalConfig) -> Dict[str, bool]:
    """Propagate the shared Netris config to all underlying demo tools."""
    results: Dict[str, bool] = {}

    save_global_config(cfg)

    # 1. netris-prometheus-exporter: netris.var & .env
    prom_dir = REPO_ROOT / "netris-prometheus-exporter"
    if prom_dir.exists():
        try:
            var_file = prom_dir / "netris.var"
            var_content = (
                f'# Generated by Demo Control Portal\n'
                f'export NETRIS_BASE_URL="{cfg.netris_url}"\n'
                f'export NETRIS_USERNAME="{cfg.netris_username}"\n'
                f'export NETRIS_PASSWORD="{cfg.netris_password}"\n'
                f'export NETRIS_VERIFY_SSL="{"true" if cfg.netris_verify_ssl else "false"}"\n'
                f'export EXPORTER_PORT="9101"\n'
            )
            with open(var_file, "w", encoding="utf-8") as f:
                f.write(var_content)

            env_file = prom_dir / ".env"
            env_content = (
                f'# Generated by Demo Control Portal\n'
                f'NETRIS_BASE_URL={cfg.netris_url}\n'
                f'NETRIS_USERNAME={cfg.netris_username}\n'
                f'NETRIS_PASSWORD={cfg.netris_password}\n'
                f'NETRIS_VERIFY_SSL={"true" if cfg.netris_verify_ssl else "false"}\n'
                f'EXPORTER_PORT=9101\n'
            )
            with open(env_file, "w", encoding="utf-8") as f:
                f.write(env_content)
            results["netris-prometheus-exporter"] = True
        except Exception as e:
            logger.error("Failed to write netris-prometheus-exporter config: %s", e)
            results["netris-prometheus-exporter"] = False

    # 2. netbox-netris: .env
    netbox_dir = REPO_ROOT / "netbox-netris"
    if netbox_dir.exists():
        try:
            netbox_env = netbox_dir / ".env"
            existing_lines = []
            if netbox_env.exists():
                with open(netbox_env, "r", encoding="utf-8") as f:
                    existing_lines = f.readlines()
            else:
                example = netbox_dir / ".env.example"
                if example.exists():
                    with open(example, "r", encoding="utf-8") as f:
                        existing_lines = f.readlines()

            # Update or append NETRIS_* keys
            new_lines = []
            keys_seen = set()
            for line in existing_lines:
                stripped = line.strip()
                if stripped.startswith("NETRIS_URL="):
                    new_lines.append(f"NETRIS_URL={cfg.netris_url}\n")
                    keys_seen.add("NETRIS_URL")
                elif stripped.startswith("NETRIS_USER="):
                    new_lines.append(f"NETRIS_USER={cfg.netris_username}\n")
                    keys_seen.add("NETRIS_USER")
                elif stripped.startswith("NETRIS_PASSWORD="):
                    new_lines.append(f"NETRIS_PASSWORD={cfg.netris_password}\n")
                    keys_seen.add("NETRIS_PASSWORD")
                else:
                    new_lines.append(line)

            if "NETRIS_URL" not in keys_seen:
                new_lines.append(f"NETRIS_URL={cfg.netris_url}\n")
            if "NETRIS_USER" not in keys_seen:
                new_lines.append(f"NETRIS_USER={cfg.netris_username}\n")
            if "NETRIS_PASSWORD" not in keys_seen:
                new_lines.append(f"NETRIS_PASSWORD={cfg.netris_password}\n")

            with open(netbox_env, "w", encoding="utf-8") as f:
                f.writelines(new_lines)
            results["netbox-netris"] = True
        except Exception as e:
            logger.error("Failed to update netbox-netris .env: %s", e)
            results["netbox-netris"] = False

    # 3. provider-portal: .env
    portal_dir = REPO_ROOT / "provider-portal"
    if portal_dir.exists():
        try:
            portal_env = portal_dir / ".env"
            if not portal_env.exists():
                example = portal_dir / ".env.example"
                if example.exists():
                    with open(example, "r", encoding="utf-8") as f:
                        content = f.read()
                    with open(portal_env, "w", encoding="utf-8") as f:
                        f.write(content)
            results["provider-portal"] = True
        except Exception as e:
            logger.error("Failed to check provider-portal .env: %s", e)
            results["provider-portal"] = False

    # 4. netris-slurm-cluster-sim
    slurm_dir = REPO_ROOT / "netris-slurm-cluster-sim"
    if slurm_dir.exists():
        try:
            slurm_env = slurm_dir / ".env"
            content = (
                f"# Generated by Demo Control Portal\n"
                f"NETRIS_URL={cfg.netris_url}\n"
                f"NETRIS_USERNAME={cfg.netris_username}\n"
                f"NETRIS_PASSWORD={cfg.netris_password}\n"
                f"NETRIS_VERIFY_SSL={'true' if cfg.netris_verify_ssl else 'false'}\n"
                f"DEFAULT_TENANT={cfg.default_tenant}\n"
                f"DEFAULT_SITE={cfg.default_site}\n"
            )
            with open(slurm_env, "w", encoding="utf-8") as f:
                f.write(content)
            results["netris-slurm-cluster-sim"] = True
        except Exception as e:
            logger.error("Failed to write netris-slurm-cluster-sim config: %s", e)
            results["netris-slurm-cluster-sim"] = False

    return results


def get_tool_config_text(tool_id: str) -> Optional[str]:
    """Retrieve raw config file text for a given tool."""
    tool_paths = {
        "netris-prometheus-exporter": REPO_ROOT / "netris-prometheus-exporter" / "netris.var",
        "netbox-netris": REPO_ROOT / "netbox-netris" / ".env",
        "provider-portal": REPO_ROOT / "provider-portal" / ".env",
        "netris-slurm-cluster-sim": REPO_ROOT / "netris-slurm-cluster-sim" / ".env",
        "chatsim": REPO_ROOT / "chatsim" / ".env",
    }
    path = tool_paths.get(tool_id)
    if path and path.exists():
        try:
            with open(path, "r", encoding="utf-8") as f:
                return f.read()
        except Exception as e:
            logger.warning("Error reading %s: %s", path, e)
    return None


def save_tool_config_text(tool_id: str, content: str) -> bool:
    """Save raw config file text for a given tool."""
    tool_paths = {
        "netris-prometheus-exporter": REPO_ROOT / "netris-prometheus-exporter" / "netris.var",
        "netbox-netris": REPO_ROOT / "netbox-netris" / ".env",
        "provider-portal": REPO_ROOT / "provider-portal" / ".env",
        "netris-slurm-cluster-sim": REPO_ROOT / "netris-slurm-cluster-sim" / ".env",
        "chatsim": REPO_ROOT / "chatsim" / ".env",
    }
    path = tool_paths.get(tool_id)
    if path:
        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            return True
        except Exception as e:
            logger.error("Error saving %s: %s", path, e)
    return False
